### ISSUE TITLE
TypeScript type-color for lowercase types

### ISSUE THREAD

**Issue by DotCoyote** [whizkydee/vscode-palenight-theme#29]
First things first: awesome theme 😄 
One wish though: type-declarations are highlighted very well, as long as they are capitalized. TypeScript often requires types written in lowercase, though.

Could you highlight lowercase-types as well? Maybe i could provide a PR for this, if this features is good for you.

**Comment by whizkydee** [comment]
Thanks for reaching out, Lars. I however do not understand what you're saying. Can you provide a screenshot or is there any other theme that does what you want?

**Comment by CinKon** [comment]
Hi, yeah sorry, could've provided some screens in the first place 😄 

![bildschirmfoto 2018-08-21 um 08 07 56](https://user-images.githubusercontent.com/3854991/44383597-80e42180-a519-11e8-8c98-5f42d3373885.jpg)

The reason that I can't simply write every type capitalized is TypeScript itself:

![bildschirmfoto 2018-08-21 um 08 08 33](https://user-images.githubusercontent.com/3854991/44383620-95281e80-a519-11e8-9d4e-48c0e5f4074a.jpg)

TypeScript sometimes REQUIRES to have types written in lowercase. And I'd like to have lowercase types highlighted the same way as capitalized types.

**Comment by CinKon** [comment]
The same goes for JSHint-Types:

![bildschirmfoto 2018-08-22 um 10 26 27](https://user-images.githubusercontent.com/3854991/44452106-e7d70880-a5f5-11e8-81a8-f898bd56d808.jpg)

**Comment by whizkydee** [comment]
This should already be fixed. Please re-open if not.
