### ISSUE TITLE
Bordered variant

### ISSUE THREAD

**Issue by anhari** [whizkydee/vscode-palenight-theme#32]
Hey, thanks for this theme! I really enjoy the aesthetic and working in it every day :)

What do you think of adding "bordered" variants with a slightly darkened background for the sidebar, terminal, et cetera?

For example:

<img width="2016" alt="screen shot 2019-01-12 at 11 37 03 am" src="https://user-images.githubusercontent.com/6628875/51075796-807e2b80-165e-11e9-91e7-af4c0ca62ff5.png">

In the screenshot above, I darkened the background color (`#292D3E`) by about 2% with the following overrides local to my config:

```
  "workbench.colorCustomizations": {
    "[Palenight Operator]": {
      "sideBar.background": "#242839",
      "activityBar.background": "#242839",
      "panel.background": "#242839",
      "terminal.background": "#242839"
    }
```

**Comment by whizkydee** [comment]
This is great @anhari! Feel free to send a PR :blush:

**Comment by whizkydee** [comment]
**Update:** v2 which was shipped today now comes with a mild contrast variant. It's still experimental and very early stages, so let me know what your thoughts are, and if you have suggestions on how it can be improved (enhancements will be rolled out in patches).

You can find it as **Palenight (Mild Contrast)**, and it looks somewhat like this:
<img width="1285" alt="Screenshot 2020-08-08 at 2 49 47 PM" src="https://user-images.githubusercontent.com/8625066/89712218-67974280-d987-11ea-889d-258c69053dbf.png">
