### ISSUE TITLE
Deeper contrast version

### ISSUE THREAD

**Issue by TylerBarnes** [whizkydee/vscode-palenight-theme#33]
Hey there, I love your theme!
Thanks for creating it.

Would you be interested in adding a variant with more contrast?
I opened the theme myself and darkened the background and I found that a lot easier to see.
I could make a PR even if you're interested.

**Comment by whizkydee** [comment]
Sure, thanks @TylerBarnes! Feel free to send in a PR.

**Comment by whizkydee** [comment]
**Update:** v2 which was shipped today now comes with a mild contrast variant. It's still experimental and very early stages, so let me know what your thoughts are, and if you have suggestions on how it can be improved (enhancements will be rolled out in patches).

You can find it as **Palenight (Mild Contrast)**, and it looks somewhat like this:
<img width="1285" alt="Screenshot 2020-08-08 at 2 49 47 PM" src="https://user-images.githubusercontent.com/8625066/89712218-67974280-d987-11ea-889d-258c69053dbf.png">
