### ISSUE TITLE
Change color for Git History

### ISSUE THREAD

**Issue by mikeerickson** [whizkydee/vscode-palenight-theme#35]
Is it possible to change these git information hints?  They are too prominent for my liking?

![image](https://user-images.githubusercontent.com/183153/51430953-00644280-1bd7-11e9-8ff3-0a978c5710cd.png)

**Comment by gcollic** [comment]
Hello,

you can override this in your personal configuration if you want, like this:

``` json
  "workbench.colorCustomizations": {
    "[Palenight Theme]": {
      "editorCodeLens.foreground": "#a38b42"
    }
  }
```
