### ISSUE TITLE
Higher contrast in Sidebar & Command Pallet

### ISSUE THREAD

**Issue by dhavalgshah** [whizkydee/vscode-palenight-theme#38]
Thank you for this great theme.

However, it needs better contrast ratio in the sidebar as well as in command pallet. In the current version, it is near impossible to read them in a low brightness setting.

Screenshot:
![vscode-palenight-theme-sidebar-contrast-issue](https://user-images.githubusercontent.com/30974879/54935867-1ebd2600-4f19-11e9-91a2-deea1c2eaf7e.png)

**Comment by 1chriis1** [comment]
Also hard to find where the edge of the sidebar or the terminal panel at the bottom is, so that you can resize them

**Comment by mraaroncruz** [comment]
I have pretty good eyesight (not to toot my own horn) and I really like this theme but I often choose the wrong file or command in the command palette. I couldn't imagine how it would be for someone without such amazing sightedness.

I also feel like this wasn't always an issue.

Is there a way to change just this color in the settings?

**Comment by mraaroncruz** [comment]
I found a workaround:
1. Go to settiings and look for `workbench.color` where you'll see `Workbench: Color Customizations`
2. Click `Edit in settiings.json`
3. Add the following to your settings.json (I picked a highlight color from the them in the editor and it is contrasty enough for me now)
```
  "workbench.colorCustomizations": {
    "[Palenight Theme]": {
      "list.focusBackground": "#212432"
    }
  },
```
Save it and the theme is now perfect! Thanks for the wonderful theme @whizkydee!

**Comment by whizkydee** [comment]
**Update:** v2 which was shipped today now comes with a mild contrast variant. It's still experimental and very early stages, so let me know what your thoughts are, and if you have suggestions on how it can be improved (enhancements will be rolled out in patches).

You can find it as **Palenight (Mild Contrast)**, and it looks somewhat like this:
<img width="1285" alt="Screenshot 2020-08-08 at 2 49 47 PM" src="https://user-images.githubusercontent.com/8625066/89712218-67974280-d987-11ea-889d-258c69053dbf.png">
