### ISSUE TITLE
No text selection highlight on extension search bar

### ISSUE THREAD

**Issue by sfrench87** [whizkydee/vscode-palenight-theme#41]
Just a small ui bug, if you search for an extension then try to highlight that search there is no highlight indicator. Love the theme by the way.

**Comment by whizkydee** [comment]
That's strange. I'll take a look.

**Comment by sfrench87** [comment]
I was just having a look myself and it seems to be the "selection.background", but the color in the extensions panel is always lighter then the source control or search panel for example.

**Comment by songhd** [comment]
Vote to this improvement

**Comment by whizkydee** [comment]
@songhd Thanks for reminding me of this. I'll give it a look this weekend and rollout a quick patch.
