### ISSUE TITLE
It needs more contrast in all places but the editor. 

### ISSUE THREAD

**Issue by ChristosBouronikos** [whizkydee/vscode-palenight-theme#42]
The frame, the terminal, the sidebar need to be a darker color, so that they contrast the main editor.
Right now it's difficult to navigate VSCode.

**Comment by whizkydee** [comment]
**Update:** v2 which was shipped today now comes with a mild contrast variant. It's still experimental and very early stages, so let me know what your thoughts are, and if you have suggestions on how it can be improved (enhancements will be rolled out in patches).

You can find it as **Palenight (Mild Contrast)**, and it looks somewhat like this:
<img width="1285" alt="Screenshot 2020-08-08 at 2 49 47 PM" src="https://user-images.githubusercontent.com/8625066/89712218-67974280-d987-11ea-889d-258c69053dbf.png">
