### ISSUE TITLE
Colors changed after latest vs code update

### ISSUE THREAD

**Issue by nealoke** [whizkydee/vscode-palenight-theme#43]
This theme is the best! For some reason the colors changed after installing the latest vs code update.

The underlined parts used to be greyish (so not really a color)

![image](https://user-images.githubusercontent.com/17417414/76324674-ab0d5800-62e6-11ea-99d6-7250199e6393.png)

**Comment by whizkydee** [comment]
Thanks for reporting! I noticed this myself and I'm working to find a fix. I'll let you know once I publish it.

**Comment by whizkydee** [comment]
**Update:** This is not an issue with the theme but rather with the latest VSCode -- affects all themes. They introduced [semantic highlighting](https://code.visualstudio.com/updates/v1_43#_typescript-semantic-highlighting) for JS/TS which is a more accurate way to apply syntax colors to tokens.

It will take a while to incorporate the patches, but keep an eye out for the update. As a temporary workaround, you can disable `semanticHighlighting` in your editor like:

```json
{
  "editor.semanticHighlighting.enabled": false
}
```

Hope that solves it for you. Cheers! 🍻

**Comment by whizkydee** [comment]
Closing as this theme will not be implementing support for semantic highlighting at this time.
