### ISSUE TITLE
the text selection is not visible at all

### ISSUE THREAD

**Issue by mohadel92** [whizkydee/vscode-palenight-theme#64]
recently the text selection is not visible at all
i cannot use the theme although i really like it and its my daily driver

<a href="https://ibb.co/RH5PWBX"><img src="https://i.ibb.co/ZTZKCYQ/Screen-Shot-2021-05-17-at-10-52-14-AM.png" alt="Screen-Shot-2021-05-17-at-10-52-14-AM" border="0"></a>

**Comment by j0k4rX** [comment]
same thing happens when selecting text in extension search area

**Comment by j0k4rX** [comment]
@whizkydee still in extension area, code selection is not bright
and it's hard to recognize

![Screenshot 2021-05-18 193836](https://user-images.githubusercontent.com/71499522/118661478-f7202a80-b810-11eb-8151-5c7a53dffb7c.jpg)

**Comment by mohadel92** [comment]
so what is the fix??
the issue was closed with no mention for any fix @whizkydee

**Comment by j0k4rX** [comment]
> so what is the fix??
> the issue was closed with no mention for any fix @whizkydee

@mohadel92 Your issue was fixed but text selection (in extension area) still lags some fix
