### ISSUE TITLE
Text Highlighted from Search Results not visible

### ISSUE THREAD

**Issue by atmosphericPerspective** [whizkydee/vscode-palenight-theme#72]
Hello,

I really like the Palenight Theme. However, one thing really bugs me: when I search for a text, the highlighted result is not visible at all
![VS_color](https://user-images.githubusercontent.com/85376034/138311266-048c9c06-1d5d-4d70-bb8b-b3d62892bf02.png)

Thank you!

**Comment by zhangao0086** [comment]
Same here...

**Comment by alleluya-young** [comment]
same for me, it's really hard to recognize

**Comment by andyunleashed** [comment]
![CleanShot 2022-05-23 at 09 50 06](https://user-images.githubusercontent.com/1426079/169781562-5e77cd3e-3e5c-482a-918a-1ce21fbfa1e5.gif)

I would like to add to this with a gif to show it as well, it's definitely a problem if you're searching and editing said result.
